//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzureEntities : DbContext
    {
        public AzureEntities()
            : base("name=AzureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CareerAccomplishment> CareerAccomplishments { get; set; }
        public virtual DbSet<CareerHistory> CareerHistories { get; set; }
        public virtual DbSet<CareerPosition> CareerPositions { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContactNote> ContactNotes { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<EducationalInstitution> EducationalInstitutions { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<NoteType> NoteTypes { get; set; }
        public virtual DbSet<ProfileAttribute> ProfileAttributes { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<SocialNetworkProfile> SocialNetworkProfiles { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetworks { get; set; }
        public virtual DbSet<SocialNetworkType> SocialNetworkTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Submodule> Submodules { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalSkill> TechnicalSkills { get; set; }
        public virtual DbSet<TechnicalSkillType> TechnicalSkillTypes { get; set; }
        public virtual DbSet<UrlSourceType> UrlSourceTypes { get; set; }
    }
}
