//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerAccomplishment
    {
        public int AccomplishmentId { get; set; }
        public string AccomplishmentDescription { get; set; }
        public int CareerHistoryId { get; set; }
    
        public virtual CareerHistory CareerHistory { get; set; }
    }
}
