//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int EducationalPathId { get; set; }
        public int ProfileId { get; set; }
        public int InstitutionId { get; set; }
        public string GraduationDate { get; set; }
        public string Curriculum { get; set; }
        public string Major { get; set; }
        public string Degree { get; set; }
    
        public virtual EducationalInstitution EducationalInstitution { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
