//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CareerHistory()
        {
            this.CareerAccomplishments = new HashSet<CareerAccomplishment>();
            this.CareerPositions = new HashSet<CareerPosition>();
        }
    
        public int CareerHistoryId { get; set; }
        public int ProfileId { get; set; }
        public int CompanyId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareerAccomplishment> CareerAccomplishments { get; set; }
        public virtual Company Company { get; set; }
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareerPosition> CareerPositions { get; set; }
    }
}
