//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int DownloadId { get; set; }
        public Nullable<int> SubmoduleId { get; set; }
        public string DownloadDescription { get; set; }
        public string DownloadUrl { get; set; }
        public int Status { get; set; }
        public int UrlSourceTypeId { get; set; }
    
        public virtual Submodule Submodule { get; set; }
        public virtual UrlSourceType UrlSourceType { get; set; }
    }
}
