//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Submodules = new HashSet<Submodule>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleDescription { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public int SecurityLevel { get; set; }
        public int SortOrder { get; set; }
        public string MaterialIcon { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submodule> Submodules { get; set; }
    }
}
