//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submodule
    {
        public int SubmoduleId { get; set; }
        public string SubmoduleDescription { get; set; }
        public int ModuleId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public int SecurityLevel { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string DownloadURL { get; set; }
        public int Status { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
