//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalSkill
    {
        public int TechnicalSkillId { get; set; }
        public string TechnicalSkillDescription { get; set; }
        public int TechnicalSkillTypeId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual TechnicalSkillType TechnicalSkillType { get; set; }
    }
}
